app = "stimular-backend"  # Substitua pelo nome do seu app no Fly.io

[build]
  image = "node:16"  # Use uma imagem base do Node.js compatível

[env]
  PORT = "3001"  # A porta que sua aplicação está utilizando

[deploy]
  strategy = "rolling"

[services]
  [[services.http]]
    internal_port = 3001  # Porta interna usada pela aplicação
    force_https = true

    [services.http.concurrency]
      soft_limit = 25
      hard_limit = 50

    [[services.http.ports]]
      port = 80
      handlers = ["http"]
    [[services.http.ports]]
      port = 443
      handlers = ["tls", "http"]
